[workspace]
resolver = "2"
members = [
  "common",
  "cpu_runner",
  "gpu_runner",
  "kernels",
  "logic"
]

[patch.crates-io]
zeroize = { git = "https://github.com/brandonros/utils", branch = "nvptx64-support" }

[patch."https://github.com/Rust-GPU/Rust-CUDA.git"]
cust = { git = "https://github.com/brandonros/Rust-CUDA.git", rev = "f21da0846e2f786caa5274100a75b8585b343a41" }
cuda_std = { git = "https://github.com/brandonros/Rust-CUDA.git", rev = "f21da0846e2f786caa5274100a75b8585b343a41" }
cuda_builder = { git = "https://github.com/brandonros/Rust-CUDA.git", rev = "f21da0846e2f786caa5274100a75b8585b343a41" }
