[workspace]
resolver = "2"
members = [
  "common",
  "cpu_runner",
  "gpu_runner",
  "kernels",
  "logic"
]

[patch.crates-io]
zeroize = { git = "https://github.com/brandonros/utils", branch = "nvptx64-support" }

[patch."https://github.com/Rust-GPU/Rust-CUDA.git"]
cust = { git = "https://github.com/brandonros/Rust-CUDA.git", rev = "7440c1ba2b8fa0546a3348f409f863c17ed3ce68" }
cuda_std = { git = "https://github.com/brandonros/Rust-CUDA.git", rev = "7440c1ba2b8fa0546a3348f409f863c17ed3ce68" }
cuda_builder = { git = "https://github.com/brandonros/Rust-CUDA.git", rev = "7440c1ba2b8fa0546a3348f409f863c17ed3ce68" }
