[workspace]
resolver = "2"
members = [
  "common",
  "cpu_runner",
  "gpu_runner",
  "kernels",
  "logic",
  "transpiler"
]

[patch.crates-io]
zeroize = { git = "https://github.com/brandonros/utils", rev = "4c9734e1ae4a6cb61db4693f9d164866f084ca97" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
