[workspace]
resolver = "2"
members = [
  "common",
  "cpu_runner",
  "gpu_runner",
  "kernels",
  "logic"
]

[patch.crates-io]
zeroize = { git = "https://github.com/brandonros/utils", branch = "nvptx64-support" }

[patch."https://github.com/Rust-GPU/Rust-CUDA.git"]
cust = { git = "https://github.com/brandonros/Rust-CUDA.git", rev = "5e2462bd04f8bc0664ba2232b41c9011ec6669d7" }
cuda_std = { git = "https://github.com/brandonros/Rust-CUDA.git", rev = "5e2462bd04f8bc0664ba2232b41c9011ec6669d7" }
cuda_builder = { git = "https://github.com/brandonros/Rust-CUDA.git", rev = "5e2462bd04f8bc0664ba2232b41c9011ec6669d7" }
