[workspace]
resolver = "2"
members = [
  "common",
  "cpu_runner",
  "gpu_runner",
  "kernels",
  "logic"
]

[patch.crates-io]
zeroize = { git = "https://github.com/brandonros/utils", branch = "nvptx64-support" }

[patch."https://github.com/Rust-GPU/Rust-CUDA.git"]
cust = { git = "https://github.com/brandonros/Rust-CUDA.git", rev = "47ca0a27aa486493857d400d695396cd2966192d" }
cuda_std = { git = "https://github.com/brandonros/Rust-CUDA.git", rev = "47ca0a27aa486493857d400d695396cd2966192d" }
cuda_builder = { git = "https://github.com/brandonros/Rust-CUDA.git", rev = "47ca0a27aa486493857d400d695396cd2966192d" }
