[package]
name = "kernels"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
logic = { path = "../logic" }
cuda_std = { git = "https://github.com/Rust-GPU/Rust-CUDA.git" }

[build-dependencies]
env_logger = "0.10"
cuda_builder = { git = "https://github.com/Rust-GPU/Rust-CUDA.git" }
