[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cuda_std = { git = "https://github.com/LegNeato/Rust-CUDA.git", rev = "3b3e0497227c913cadf54310f18e4eda8b10f5e3" }
sha2 = { version = "0.10.8", default-features = false }
curve25519-dalek = { path = "../curve25519-dalek/curve25519-dalek", default-features = false, features = ["alloc", "precomputed-tables"] }
rand_core = { version = "0.9.3" }
rand_xorshift = { version = "0.4.0", default-features = false }
rand_xoshiro = { version = "0.7.0", default-features = false }

[build-dependencies]
cuda_builder = { git = "https://github.com/LegNeato/Rust-CUDA.git", rev = "3b3e0497227c913cadf54310f18e4eda8b10f5e3" }
