[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cuda_std = { git = "https://github.com/LegNeato/Rust-CUDA.git", rev = "fab74552c00f1ecaf911a1fff9214f29ae028655" }
ed25519-compact = { path = "./ed25519", features = ["cuda"] }
sha2 = { version = "0.10.8", default-features = false }
curve25519-dalek = { version = "4.1.3", default-features = false, features = ["alloc", "precomputed-tables"] }
bs58 = { version = "0.5.1", default-features = false }
rand_core = { version = "0.9.3" }
rand_xorshift = { version = "0.4.0", default-features = false }
rand_xoshiro = { version = "0.7.0", default-features = false }

[build-dependencies]
cuda_builder = { git = "https://github.com/LegNeato/Rust-CUDA.git", rev = "fab74552c00f1ecaf911a1fff9214f29ae028655" }
