[package]
name = "gpu_runner"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4.3"
rand = "0.8"
common = { path = "../common" }
logic = { path = "../logic" }
cust = { git = "https://github.com/brandonros/Rust-CUDA.git", rev = "10cbfd2bb8fbe54b42b891b270da821512c56409" }
