[package]
name = "gpu_runner"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4.3"
rand = "0.8"
common = { path = "../common" }
cust = { git = "https://github.com/Rust-GPU/Rust-CUDA.git" }

[build-dependencies]
cuda_builder = { git = "https://github.com/Rust-GPU/Rust-CUDA.git" }
